"""Generate a local Pyroscope source-code map for the LGTM dev stack."""

from __future__ import annotations

import argparse
import collections.abc as cabc
import contextlib
import importlib.metadata
import importlib.util
import pathlib
import sys
from dataclasses import dataclass

ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / ".tmp" / "lgtm" / ".pyroscope.yaml"


@dataclass(frozen=True, slots=True)
class LocalSource:
    """A repository-local source-code target."""

    path: str


@dataclass(frozen=True, slots=True)
class GitHubSource:
    """A GitHub source-code target."""

    owner: str
    repo: str
    ref: str
    path: str


@dataclass(frozen=True, slots=True)
class SourceMapping:
    """One Pyroscope source-code mapping."""

    prefixes: tuple[str, ...]
    language: str
    source: LocalSource | GitHubSource


@dataclass(frozen=True, slots=True)
class PythonPackageMappingSpec:
    """How an installed Python package maps back to upstream source."""

    module_name: str
    distribution_name: str
    owner: str
    repo: str
    source_path: str


_PYTHON_PACKAGE_SPECS: tuple[PythonPackageMappingSpec, ...] = (
    PythonPackageMappingSpec(
        module_name="opentelemetry.exporter.otlp.proto.common",
        distribution_name="opentelemetry-exporter-otlp-proto-common",
        owner="open-telemetry",
        repo="opentelemetry-python",
        source_path=(
            "exporter/opentelemetry-exporter-otlp-proto-common/src/"
            "opentelemetry/exporter/otlp/proto/common"
        ),
    ),
    PythonPackageMappingSpec(
        module_name="opentelemetry.exporter.otlp.proto.http",
        distribution_name="opentelemetry-exporter-otlp-proto-http",
        owner="open-telemetry",
        repo="opentelemetry-python",
        source_path=(
            "exporter/opentelemetry-exporter-otlp-proto-http/src/"
            "opentelemetry/exporter/otlp/proto/http"
        ),
    ),
    PythonPackageMappingSpec(
        module_name="opentelemetry.sdk",
        distribution_name="opentelemetry-sdk",
        owner="open-telemetry",
        repo="opentelemetry-python",
        source_path="opentelemetry-sdk/src/opentelemetry/sdk",
    ),
    PythonPackageMappingSpec(
        module_name="opentelemetry.proto",
        distribution_name="opentelemetry-proto",
        owner="open-telemetry",
        repo="opentelemetry-python",
        source_path="opentelemetry-proto/src/opentelemetry/proto",
    ),
    PythonPackageMappingSpec(
        module_name="opentelemetry.instrumentation.sqlite3",
        distribution_name="opentelemetry-instrumentation-sqlite3",
        owner="open-telemetry",
        repo="opentelemetry-python-contrib",
        source_path=(
            "instrumentation/opentelemetry-instrumentation-sqlite3/src/"
            "opentelemetry/instrumentation/sqlite3"
        ),
    ),
    PythonPackageMappingSpec(
        module_name="opentelemetry.instrumentation.asyncio",
        distribution_name="opentelemetry-instrumentation-asyncio",
        owner="open-telemetry",
        repo="opentelemetry-python-contrib",
        source_path=(
            "instrumentation/opentelemetry-instrumentation-asyncio/src/"
            "opentelemetry/instrumentation/asyncio"
        ),
    ),
)


def build_mappings(
    *,
    repo_root: pathlib.Path,
    module_origins: cabc.Mapping[str, pathlib.Path | str] | None = None,
    distribution_versions: cabc.Mapping[str, str] | None = None,
) -> list[SourceMapping]:
    """Build Pyroscope mappings for this checkout and known dependencies."""
    del repo_root
    mappings = [
        SourceMapping(
            prefixes=("src",),
            language="python",
            source=LocalSource(path="src"),
        ),
        SourceMapping(
            prefixes=("scripts",),
            language="python",
            source=LocalSource(path="scripts"),
        ),
    ]

    origins = module_origins if module_origins is not None else _discover_module_origins()
    versions = (
        distribution_versions
        if distribution_versions is not None
        else _discover_distribution_versions(_PYTHON_PACKAGE_SPECS)
    )
    for spec in _PYTHON_PACKAGE_SPECS:
        origin = origins.get(spec.module_name)
        version = versions.get(spec.distribution_name)
        if origin is None or version is None:
            continue
        mappings.append(
            SourceMapping(
                prefixes=(spec.module_name.replace(".", "/"),),
                language="python",
                source=GitHubSource(
                    owner=spec.owner,
                    repo=spec.repo,
                    ref=f"v{version}",
                    path=spec.source_path,
                ),
            ),
        )
    return mappings


def render_pyroscope_yaml(mappings: cabc.Sequence[SourceMapping]) -> str:
    """Render ``mappings`` as a Pyroscope source-code YAML document."""
    lines = [
        "# Generated by scripts/lgtm/generate_pyroscope_source_map.py.",
        "# Generated output uses repository and package-relative prefixes.",
        "version: v1",
        "source_code:",
    ]
    if not mappings:
        lines.append("  mappings: []")
        return "\n".join(lines) + "\n"

    lines.append("  mappings:")
    for mapping in mappings:
        lines.append("    - path:")
        lines.extend(f"        - prefix: {prefix}" for prefix in mapping.prefixes)
        lines.append(f"      language: {mapping.language}")
        lines.append("      source:")
        if isinstance(mapping.source, LocalSource):
            lines.append("        local:")
            lines.append(f"          path: {mapping.source.path}")
        else:
            lines.append("        github:")
            lines.append(f"          owner: {mapping.source.owner}")
            lines.append(f"          repo: {mapping.source.repo}")
            lines.append(f"          ref: {mapping.source.ref}")
            lines.append(f"          path: {mapping.source.path}")
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=pathlib.Path,
        default=ROOT,
        help="Repository checkout root used for local source prefixes.",
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=DEFAULT_OUTPUT,
        help="Output path. Use '-' to write the YAML to stdout.",
    )
    return parser


def main(argv: cabc.Sequence[str] | None = None) -> int:
    """Generate the source map."""
    args = build_parser().parse_args(argv)
    mappings = build_mappings(repo_root=args.repo_root)
    rendered = render_pyroscope_yaml(mappings)
    if str(args.output) == "-":
        sys.stdout.write(rendered)
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


def _discover_module_origins() -> dict[str, pathlib.Path]:
    """Return import origins for package specs that are importable."""
    origins: dict[str, pathlib.Path] = {}
    for spec in _PYTHON_PACKAGE_SPECS:
        with contextlib.suppress(Exception):
            module_spec = importlib.util.find_spec(spec.module_name)
            origin = getattr(module_spec, "origin", None)
            if origin and origin not in {"built-in", "frozen"}:
                origins[spec.module_name] = pathlib.Path(origin)
                continue
            search_locations = getattr(module_spec, "submodule_search_locations", None)
            if search_locations:
                origins[spec.module_name] = pathlib.Path(next(iter(search_locations)))
    return origins


def _discover_distribution_versions(
    specs: cabc.Iterable[PythonPackageMappingSpec],
) -> dict[str, str]:
    """Return installed versions for package specs that are installed."""
    versions: dict[str, str] = {}
    for spec in specs:
        with contextlib.suppress(importlib.metadata.PackageNotFoundError):
            versions[spec.distribution_name] = importlib.metadata.version(spec.distribution_name)
    return versions


if __name__ == "__main__":
    raise SystemExit(main())
